with-expecter: true
packages:
  github.com/bukka/wst/app:
    config:
      dir: mocks/appMocks
      outpkg: appMocks
    interfaces:
      Env: {}
  github.com/bukka/wst/conf/loader:
    config:
      dir: mocks/confMocks
      outpkg: confMocks
    interfaces:
      LoadedConfig: {}
      Loader: {}
