with-expecter: true
packages:
  github.com/bukka/wst/app:
    config:
      dir: mocks/app
    interfaces:
      Foundation: {}
      VegetaAttacker: {}
      VegetaMetrics: {}
  github.com/bukka/wst/conf/loader:
    config:
      dir: mocks/conf/loader
    interfaces:
      LoadedConfig: {}
      Loader: {}
  github.com/bukka/wst/conf/merger:
    config:
      dir: mocks/conf/merger
    interfaces:
      Merger: {}
  github.com/bukka/wst/conf/overwrites:
    config:
      dir: mocks/conf/overwrites
    interfaces:
      Overwriter: {}
  github.com/bukka/wst/conf/parser:
    config:
      dir: mocks/conf/parser
    interfaces:
      Parser: {}
  github.com/bukka/wst/conf/parser/factory:
    config:
      dir: mocks/conf/parser/factory
    interfaces:
      Functions: {}
